//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace Wedol.SteelSeries.Sonar
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AnalyticsEvent
    {

        [System.Text.Json.Serialization.JsonPropertyName("event")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Event { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("properties")]
        public System.Collections.Generic.IDictionary<string, string?>? Properties { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppStatus
    {

        [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
        public bool IsEnabled { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isOnboardingDone")]
        public bool IsOnboardingDone { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("mode")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ModeId>))]
        public ModeId Mode { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("areEndpointsConfigured")]
        public bool AreEndpointsConfigured { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("devices")]
        public System.Collections.Generic.ICollection<VadStatus>? Devices { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AudioDevice
    {

        [System.Text.Json.Serialization.JsonPropertyName("friendlyName")]
        public string? FriendlyName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("dataFlow")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceDataFlow>))]
        public DeviceDataFlow DataFlow { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceRole>))]
        public DeviceRole Role { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("channels")]
        public int Channels { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("defaultRole")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceDefaultRoles>))]
        public DeviceDefaultRoles DefaultRole { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("fwUpdateRequired")]
        public bool FwUpdateRequired { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<State>))]
        public State State { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isVad")]
        public bool IsVad { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AudioSample
    {

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceRole>))]
        public DeviceRole Role { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isPlaying")]
        public bool IsPlaying { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AudioSession
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("processName")]
        public string? ProcessName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("processId")]
        public int ProcessId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isSystemSound")]
        public bool IsSystemSound { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AudioSessionState>))]
        public AudioSessionState State { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        public string? DisplayName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isRoutingErrorProne")]
        public bool IsRoutingErrorProne { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("routingErrorDetected")]
        public bool RoutingErrorDetected { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AudioSessionState
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"inactive")]
        Inactive = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"active")]
        Active = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"expired")]
        Expired = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ChatMix
    {

        [System.Text.Json.Serialization.JsonPropertyName("balance")]
        public float Balance { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("state")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ChatMixState>))]
        public ChatMixState State { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ChatMixState
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"enabled")]
        Enabled = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"finiteWheel")]
        FiniteWheel = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"differentDeviceSelected")]
        DifferentDeviceSelected = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"noDeviceSelected")]
        NoDeviceSelected = 3,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ClassicRedirection
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<RedirectionId>))]
        public RedirectionId Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
        public string? DeviceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isRunning")]
        public bool IsRunning { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Config
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public System.Guid Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.StringLength(40)]
        public string? Name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
        public System.DateTimeOffset UpdatedAt { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("virtualAudioDevice")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<VirtualAudioDevice>))]
        public VirtualAudioDevice VirtualAudioDevice { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public object? Data { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("schemaVersion")]
        public int SchemaVersion { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isPreset")]
        public bool IsPreset { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("defaultData")]
        public object? DefaultData { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("image")]
        public string? Image { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
        public bool IsFavorite { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("favoritePosition")]
        public int FavoritePosition { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("releaseVersion")]
        public string? ReleaseVersion { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ConfigDataForSharing
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public object? Data { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("schemaVersion")]
        public int SchemaVersion { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("virtualAudioDevice")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<VirtualAudioDevice>))]
        public VirtualAudioDevice VirtualAudioDevice { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ConfigOption
    {

        [System.Text.Json.Serialization.JsonPropertyName("virtualAudioDevice")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<VirtualAudioDevice>))]
        public VirtualAudioDevice VirtualAudioDevice { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isFavoriteLimitReached")]
        public bool IsFavoriteLimitReached { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ConfigStatus
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DeviceAudioSessions
    {

        [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
        public string? DeviceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceRole>))]
        public DeviceRole Role { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("dataFlow")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceDataFlow>))]
        public DeviceDataFlow DataFlow { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("audioSessions")]
        public System.Collections.Generic.ICollection<AudioSession>? AudioSessions { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum DeviceDataFlow
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"render")]
        Render = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"capture")]
        Capture = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"all")]
        All = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum DeviceDefaultRoles
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"console")]
        Console = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"multimedia")]
        Multimedia = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"communications")]
        Communications = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"all")]
        All = 3,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DeviceOutData
    {

        [System.Text.Json.Serialization.JsonPropertyName("selectedDeviceOut")]
        public string? SelectedDeviceOut { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deviceOutSettings")]
        public System.Collections.Generic.ICollection<DeviceOutSetting>? DeviceOutSettings { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DeviceOutSetting
    {

        [System.Text.Json.Serialization.JsonPropertyName("volume")]
        public float Volume { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("mute")]
        public bool Mute { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("feature")]
        public string? Feature { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum DeviceRole
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"none")]
        None = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"chatRender")]
        ChatRender = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"game")]
        Game = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"chatCapture")]
        ChatCapture = 3,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"stream")]
        Stream = 4,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"media")]
        Media = 5,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"aux")]
        Aux = 6,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DeviceRoleExtendedFallbackDeviceDataIEnumerableKeyValuePair
    {

        [System.Text.Json.Serialization.JsonPropertyName("key")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceRole>))]
        public DeviceRole Key { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public System.Collections.Generic.ICollection<ExtendedFallbackDeviceData>? Value { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DeviceVolume
    {

        [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
        public string? DeviceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("volume")]
        public float Volume { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExportRequestData
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExportedConfigLink
    {

        [System.Text.Json.Serialization.JsonPropertyName("shareUrl")]
        public string? ShareUrl { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ExtendedFallbackDeviceData
    {

        [System.Text.Json.Serialization.JsonPropertyName("isPrevious")]
        public bool IsPrevious { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isNext")]
        public bool IsNext { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("label")]
        public string? Label { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isActive")]
        public bool IsActive { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isSteelseriesWirelessSupported")]
        public bool IsSteelseriesWirelessSupported { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isSteelseriesWirelessConnected")]
        public bool IsSteelseriesWirelessConnected { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isExcluded")]
        public bool IsExcluded { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Feature
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"unknown")]
        Unknown = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"software_chatmix_finite")]
        Software_chatmix_finite = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"software_chatmix_infinite")]
        Software_chatmix_infinite = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"sonar_ciaran")]
        Sonar_ciaran = 3,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"sonar_ciaran7")]
        Sonar_ciaran7 = 4,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"sonar_ciaran9")]
        Sonar_ciaran9 = 5,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"sonar_fw_update_required")]
        Sonar_fw_update_required = 6,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"bindable")]
        Bindable = 7,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"headphone_out")]
        Headphone_out = 8,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"line_out")]
        Line_out = 9,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"built_in_eq")]
        Built_in_eq = 10,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FeatureData
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Feature>))]
        public Feature Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
        public bool IsEnabled { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public object? Data { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InAppToastMessage
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        public string? Title { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("shortTitle")]
        public string? ShortTitle { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("mediaSrc")]
        public string? MediaSrc { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("mimeType")]
        public string? MimeType { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buttonText")]
        public string? ButtonText { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("buttonLink")]
        public string? ButtonLink { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class KeyboardShortcut
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("trigger_data")]
        public string? Trigger_data { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("default_trigger")]
        public string? Default_trigger { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LinkAllData
    {

        [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
        public bool IsEnabled { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("classicRedirections")]
        public System.Collections.Generic.ICollection<ClassicRedirection>? ClassicRedirections { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("devices")]
        public System.Collections.Generic.ICollection<DeviceRoleExtendedFallbackDeviceDataIEnumerableKeyValuePair>? Devices { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("shortcuts")]
        public System.Collections.Generic.ICollection<KeyboardShortcut>? Shortcuts { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ModeId
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"classic")]
        Classic = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"stream")]
        Stream = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OnBoardingPayload
    {

        [System.Text.Json.Serialization.JsonPropertyName("finished")]
        public bool Finished { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OnboardingDevices
    {

        [System.Text.Json.Serialization.JsonPropertyName("devices")]
        public Devices? Devices { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum OverlayPosition
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"TopRight")]
        TopRight = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"CenterRight")]
        CenterRight = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"BottomRight")]
        BottomRight = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"TopLeft")]
        TopLeft = 3,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"CenterLeft")]
        CenterLeft = 4,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"BottomLeft")]
        BottomLeft = 5,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OverlaySettingsData
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("localization")]
        public string? Localization { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
        public bool IsEnabled { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("position")]
        public int Position { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OverlaysSettings
    {

        [System.Text.Json.Serialization.JsonPropertyName("settings")]
        public System.Collections.Generic.ICollection<OverlaySettingsData>? Settings { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("subAppOverlaysEnabled")]
        public bool SubAppOverlaysEnabled { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Preset
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public System.Guid Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isFavorite")]
        public bool IsFavorite { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("favoritePosition")]
        public int FavoritePosition { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Profile
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isGame")]
        public bool IsGame { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("gameImagePath")]
        public string? GameImagePath { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isCustom")]
        public bool IsCustom { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("customId")]
        public string? CustomId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("sonarConfigId")]
        public string? SonarConfigId { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum RedirectionId
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"game")]
        Game = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"chat")]
        Chat = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"mic")]
        Mic = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"micPlayer")]
        MicPlayer = 3,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"micCopy")]
        MicCopy = 4,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"streamingCopy")]
        StreamingCopy = 5,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"media")]
        Media = 6,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"aux")]
        Aux = 7,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RedirectionVolumes
    {

        [System.Text.Json.Serialization.JsonPropertyName("stream")]
        public Stream? Stream { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("classic")]
        public VolumeSettings Classic { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedConfig
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public ConfigDataForSharing Data { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("metadata")]
        public SharedConfigMetadata Metadata { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SharedConfigMetadata
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("author")]
        public string? Author { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum State
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"active")]
        Active = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"disabled")]
        Disabled = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"activeOrDisabled")]
        ActiveOrDisabled = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"notpresent")]
        Notpresent = 3,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"unplugged")]
        Unplugged = 4,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"all")]
        All = 5,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SteelSeriesAudioDevice
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("imageUrl")]
        public string? ImageUrl { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("captureId")]
        public string? CaptureId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("renderId")]
        public string? RenderId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("humanReadableName")]
        public string? HumanReadableName { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StreamRedirection
    {

        [System.Text.Json.Serialization.JsonPropertyName("streamRedirectionId")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<StreamRedirectionId>))]
        public StreamRedirectionId StreamRedirectionId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("deviceId")]
        public string? DeviceId { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<StreamRedirectionStatus> Status { get; set; } = new System.Collections.ObjectModel.Collection<StreamRedirectionStatus>();

        [System.Text.Json.Serialization.JsonPropertyName("isRunning")]
        public bool IsRunning { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum StreamRedirectionId
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"streaming")]
        Streaming = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"monitoring")]
        Monitoring = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"mic")]
        Mic = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StreamRedirectionStatus
    {

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceRole>))]
        public DeviceRole Role { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
        public bool IsEnabled { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Type
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"VolumeUp")]
        VolumeUp = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"VolumeDown")]
        VolumeDown = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"Mute")]
        Mute = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"NextDevice")]
        NextDevice = 3,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"PreviousDevice")]
        PreviousDevice = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class VadConfig
    {

        [System.Text.Json.Serialization.JsonPropertyName("globalEnableState")]
        public bool GlobalEnableState { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class VadStatus
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("dataFlow")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceDataFlow>))]
        public DeviceDataFlow DataFlow { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("virtualAudioDevice")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceRole>))]
        public DeviceRole VirtualAudioDevice { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("defaultRole")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DeviceDefaultRoles>))]
        public DeviceDefaultRoles DefaultRole { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("isChannelEnabled")]
        public bool IsChannelEnabled { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("streamRedirectionDevice")]
        public string? StreamRedirectionDevice { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("streamRedirectionDeviceName")]
        public string? StreamRedirectionDeviceName { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("config")]
        [System.ComponentModel.DataAnnotations.Required]
        public ConfigStatus Config { get; set; } = new ConfigStatus();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum VirtualAudioDevice
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"game")]
        Game = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"chatRender")]
        ChatRender = 1,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"chatCapture")]
        ChatCapture = 2,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"media")]
        Media = 3,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"aux")]
        Aux = 4,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class VolumeInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("masters")]
        public RedirectionVolumes Masters { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("devices")]
        public Devices2? Devices { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class VolumeSettings
    {

        [System.Text.Json.Serialization.JsonPropertyName("volume")]
        public float Volume { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("muted")]
        public bool Muted { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Devices
    {

        [System.Text.Json.Serialization.JsonPropertyName("none")]
        public string None { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("chatRender")]
        public string ChatRender { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("game")]
        public string Game { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("chatCapture")]
        public string ChatCapture { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("stream")]
        public string Stream { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("media")]
        public string Media { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("aux")]
        public string Aux { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Stream
    {

        [System.Text.Json.Serialization.JsonPropertyName("streaming")]
        public VolumeSettings Streaming { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("monitoring")]
        public VolumeSettings Monitoring { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("mic")]
        public VolumeSettings Mic { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Devices2
    {

        [System.Text.Json.Serialization.JsonPropertyName("none")]
        public RedirectionVolumes None { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("chatRender")]
        public RedirectionVolumes ChatRender { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("game")]
        public RedirectionVolumes Game { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("chatCapture")]
        public RedirectionVolumes ChatCapture { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("stream")]
        public RedirectionVolumes Stream { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("media")]
        public RedirectionVolumes Media { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("aux")]
        public RedirectionVolumes Aux { get; set; } = default!;

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string? Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception? innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception? innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765